In [17]:
import pandas as pd
df = pd.read_csv("Extracted.csv")
print(df.head())

   Average_Rating     Brand        Date Express    Get_It_BY  \
0             5.0     TYCOM  2024-10-10       Y  11 - 12 Oct
1             NaN      MELA  2024-10-10       Y       12 Oct
2             NaN   Generic  2024-10-10       Y  11 - 12 Oct
3             4.8  Bernessi  2024-10-10       Y  11 - 12 Oct
4             4.1   Fitness  2024-10-10       Y       12 Oct

                                                Link  \
0  https://www.noon.com//uae-en/tycom-resistance-...
1  https://www.noon.com//uae-en/mela-non-slip-yog...
2  https://www.noon.com//uae-en/5-pieces-sports-w...
3  https://www.noon.com//uae-en/8mm-yoga-mat-with...
4  https://www.noon.com//uae-en/anti-slip-yoga-ma...

                                                Name  Price Rating_count  \
0  TYCOM Tycom Resistance Loop Bands- Resistance ...   28.9            1
1  MELA MELA Non-Slip Yoga Mat for Home Gym - 6mm...   79.0          NaN
2  Generic 5 Pieces Sports Wicking Instant Dry Co...   30.5          NaN
3  Bernessi 8MM Yoga Mat with Carrying Strap Anti...   69.9           51
4  Fitness World Anti-Slip Yoga Mat With Carry St...   35.0          213

   Sale_price Sponsered
0       49.00         Y
1      119.00         Y
2       59.95         Y
3      165.00       NaN
4         NaN       NaN

In [19]:
#finding Most expensive product and Cheapest Product 

max = df['Price'][0]
min = df['Price'][0]
for i in df['Price']:
    max = i if i > max else max
    min = i if i < min else min  
print(df.loc[df['Price'] == max])
print(df.loc[df['Price'] == min])


print("===============================================================================")

#Also sorting the data based on Price valeue

Sorted = df.sort_values('Price')
Sorted

     Average_Rating    Brand        Date Express    Get_It_BY  \
254             5.0  Generic  2024-10-10       Y  11 - 12 Oct

                                                  Link  \
254  https://www.noon.com//uae-en/punching-bag-fitn...

                                                  Name  Price Rating_count  \
254  Generic Punching Bag Fitness Boxing Equipment ...  600.0            1

     Sale_price Sponsered
254       750.0       NaN
     Average_Rating    Brand        Date Express    Get_It_BY  \
137             NaN  Applied  2024-10-10       Y  11 - 12 Oct

                                                  Link  \
137  https://www.noon.com//uae-en/gym-towel-black/Z...

                                    Name  Price Rating_count  Sale_price  \
137  Applied Nutrition Gym Towel, Black    11.1          NaN         NaN

    Sponsered
137       NaN
===============================================================================

,Average_Rating,Brand,Date,Express,Get_It_BY,Link,Name,Price,Rating_count,Sale_price,Sponsered
137,NaN,Applied,2024-10-10,Y,11 - 12 Oct,https://www.noon.com//uae-en/gym-towel-black/Z...,"Applied Nutrition Gym Towel, Black",11.10,NaN,NaN,NaN
85,3.7,Generic,2024-10-10,Y,12 Oct,https://www.noon.com//uae-en/back-massager-str...,Generic Back Massager Stretcher 40x25x3cm,14.00,99,29.00,NaN
231,4.2,Kanteen,2024-10-10,NaN,13 Oct,https://www.noon.com//uae-en/5-piece-exercise-...,Kanteen Store 5-Piece Exercise Resistance Loop...,16.95,5,NaN,NaN
220,3.7,Generic,2024-10-10,Y,12 Oct,https://www.noon.com//uae-en/sweat-absorbent-n...,Generic Sweat Absorbent Non-Slip Yoga Socks,20.00,4,25.95,NaN
68,4.7,CYTHERIA,2024-10-10,NaN,NaN,https://www.noon.com//uae-en/wolf-tooth-hollow...,CYTHERIA Wolf Tooth Hollow Foam Roller 33x14cm,21.00,12,42.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...
113,NaN,Cool,2024-10-10,Y,11 - 12 Oct,https://www.noon.com//uae-en/pilates-yoga-wedg...,Cool Baby Style Pilates Yoga Wedge Massage Cor...,237.20,NaN,329.00,NaN
98,NaN,Cool,2024-10-10,Y,11 - 12 Oct,https://www.noon.com//uae-en/pilates-yoga-wedg...,Cool Baby Style Pilates Yoga Wedge Massage Cor...,257.00,NaN,329.00,NaN
177,NaN,Yalla,2024-10-10,NaN,13 Oct,https://www.noon.com//uae-en/yalla-homegym-30m...,Yalla HomeGym YALLA HomeGym 30MM EXTRA THICK R...,270.00,NaN,NaN,NaN
175,NaN,Manduka,2024-10-10,NaN,16 Oct,https://www.noon.com//uae-en/prolite-yoga-mat-...,Manduka Prolite Yoga Mat Indulge 71 Inch,490.00,NaN,NaN,NaN
254,5.0,Generic,2024-10-10,Y,11 - 12 Oct,https://www.noon.com//uae-en/punching-bag-fitn...,Generic Punching Bag Fitness Boxing Equipment ...,600.00,1,750.00,NaN

In [29]:
# for referencing
#brand = len(df.loc[df['Brand'] == "Generic"])
#print(brand)

#Making  a list of uniqe Brand
Brands_name  = []
for i in df['Brand']:
    if i not in Brands_name:
        Brands_name.append(i)
for i in Brands_name:
    print(i)

TYCOM
MELA
Generic
Bernessi
Fitness
Maston
MahMir
NNEWVANTE
LYNLYN
Spall
Pro
body
URbazaar
ORiTi
MoKo
Emfil
GROIC
RIGID
BODY
321
U-pick
YooA
SKY-TOUCH
Ab
WENBO
YQbest
Gaiam
LIMOS
yoga
CYTHERIA
Rock
SYOSI
Adidas
Sable
Arabest
Cool
Garlo
PUMA
Kanteen
TOEON
Applied
Inder
DubaiGallery
UKR
Motim
Depend
ZCM-HAPPY
Y&D
SkyLand
Excefore
limodo
Body
BOLDFIT
HaveDream
Manduka
Yalla
DBLEW
RIOXS
SHAPE
Vitacelli
DEGA
TA
Toshionics
QiaoKai
RATSAW
MissTiara
Prickly
Reebok
Nivia

In [31]:
# Number of Products from Each brand in dictionry

NoOfProductForEachBrand = {}
for i in Brands_name:
    No_products = len(df.loc[df['Brand'] == i])
    NoOfProductForEachBrand[i] = No_products
print(NoOfProductForEachBrand)

{'TYCOM': 4, 'MELA': 9, 'Generic': 47, 'Bernessi': 6, 'Fitness': 10, 'Maston': 5, 'MahMir': 14, 'NNEWVANTE': 4, 'LYNLYN': 4, 'Spall': 7, 'Pro': 1, 'body': 5, 'URbazaar': 5, 'ORiTi': 5, 'MoKo': 1, 'Emfil': 2, 'GROIC': 18, 'RIGID': 3, 'BODY': 6, '321': 1, 'U-pick': 1, 'YooA': 2, 'SKY-TOUCH': 3, 'Ab': 1, 'WENBO': 8, 'YQbest': 1, 'Gaiam': 4, 'LIMOS': 1, 'yoga': 2, 'CYTHERIA': 1, 'Rock': 3, 'SYOSI': 3, 'Adidas': 11, 'Sable': 1, 'Arabest': 2, 'Cool': 5, 'Garlo': 1, 'PUMA': 1, 'Kanteen': 7, 'TOEON': 1, 'Applied': 1, 'Inder': 1, 'DubaiGallery': 1, 'UKR': 1, 'Motim': 1, 'Depend': 1, 'ZCM-HAPPY': 4, 'Y&D': 1, 'SkyLand': 2, 'Excefore': 1, 'limodo': 2, 'Body': 3, 'BOLDFIT': 1, 'HaveDream': 1, 'Manduka': 1, 'Yalla': 1, 'DBLEW': 2, 'RIOXS': 2, 'SHAPE': 1, 'Vitacelli': 1, 'DEGA': 1, 'TA': 1, 'Toshionics': 2, 'QiaoKai': 1, 'RATSAW': 1, 'MissTiara': 1, 'Prickly': 1, 'Reebok': 2, 'Nivia': 1}

In [25]:
# print the brand name and no of products each brand

for k, v in NoOfProductForEachBrand.items():
    print(f'{k} have {v} products')

TYCOM have 4 products
MELA have 9 products
Generic have 47 products
Bernessi have 6 products
Fitness have 10 products
Maston have 5 products
MahMir have 14 products
NNEWVANTE have 4 products
LYNLYN have 4 products
Spall have 7 products
Pro have 1 products
body have 5 products
URbazaar have 5 products
ORiTi have 5 products
MoKo have 1 products
Emfil have 2 products
GROIC have 18 products
RIGID have 3 products
BODY have 6 products
321 have 1 products
U-pick have 1 products
YooA have 2 products
SKY-TOUCH have 3 products
Ab have 1 products
WENBO have 8 products
YQbest have 1 products
Gaiam have 4 products
LIMOS have 1 products
yoga have 2 products
CYTHERIA have 1 products
Rock have 3 products
SYOSI have 3 products
Adidas have 11 products
Sable have 1 products
Arabest have 2 products
Cool have 5 products
Garlo have 1 products
PUMA have 1 products
Kanteen have 7 products
TOEON have 1 products
Applied have 1 products
Inder have 1 products
DubaiGallery have 1 products
UKR have 1 products
Motim have 1 products
Depend have 1 products
ZCM-HAPPY have 4 products
Y&D have 1 products
SkyLand have 2 products
Excefore have 1 products
limodo have 2 products
Body have 3 products
BOLDFIT have 1 products
HaveDream have 1 products
Manduka have 1 products
Yalla have 1 products
DBLEW have 2 products
RIOXS have 2 products
SHAPE have 1 products
Vitacelli have 1 products
DEGA have 1 products
TA have 1 products
Toshionics have 2 products
QiaoKai have 1 products
RATSAW have 1 products
MissTiara have 1 products
Prickly have 1 products
Reebok have 2 products
Nivia have 1 products

In [27]:
df.groupby(['Brand']).count()

,Average_Rating,Date,Express,Get_It_BY,Link,Name,Price,Rating_count,Sale_price,Sponsered
Brand,,,,,,,,,,
321,1,1,1,1,1,1,1,1,0,0
Ab,1,1,0,1,1,1,1,1,1,0
Adidas,2,11,11,11,11,11,11,2,11,0
Applied,0,1,1,1,1,1,1,0,0,0
Arabest,1,2,2,2,2,2,2,1,0,0
...,...,...,...,...,...,...,...,...,...,...
YooA,0,2,2,2,2,2,2,0,2,0
ZCM-HAPPY,4,4,4,4,4,4,4,4,1,0
body,5,5,1,5,5,5,5,5,3,0
limodo,2,2,2,2,2,2,2,2,2,0
yoga,2,2,2,2,2,2,2,2,2,0